imports:
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    translator: ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: "%assetVersion%"
        #assets_version_format:  "%%s?ver=%%s"
        #assets_base_url: [ /%assets_folder ]

    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets:
        version: null
        version_format:       '%%s?%%s'


# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    auto_reload: true
    globals:
        defaultAvatarPath: "%defaultavatarpath%"
        defaultUserAvatar: "%defaultuseravatar%"
        facebookAppId: "%facebookAppId%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ SomeBundle ]
    #read_from:      "%kernel.root_dir%/../web/bundles/ilkerozcanportfolio/assets/"
    write_to:       "%kernel.root_dir%/../src/ilkerozcan/PortfolioBundle/Resources/public/assets/"
    #java: /usr/bin/java
    filters:
        uglifycss:
            bin: /usr/local/bin/uglifycss
        uglifyjs:
            bin: /usr/local/bin/uglifyjs
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
    #base_url:
        #default: /build

# Doctrine Configuration
doctrine:
    dbal:
        #for more than once connections
        #default_connection: default
        #connections:
            #default:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
        mapping_types:
            enum:       string

            #secondDB
            #sqliteDB:
                #driver: pdo_sqlite
                #user: "%sqlite_dbuser%"
                #password: "%sqlite_password%"
                #path: "%sqlite_path%"
                #memory: false

    orm:
        #for more than once connections
        #default_entity_manager: default
        #entity_managers:
            #default:
                #connection: default
                #naming_strategy: doctrine.orm.naming_strategy.underscore
                #mappings:
                    #Bundle1: ~
                    #Bundle2: ~
                    #Bundle3: ~
                    #MaxGlobalBundle: ~
            #sqliteDB:
                #naming_strategy: doctrine.orm.naming_strategy.underscore
                #connection: usertimeline
                #mappings:
                    #Bundle4: ~

        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true



# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    port:      "%mailer_port%"
    encryption: "%mailer_encryption%"
    auth_mode:  "%mailer_authmode%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: SomeBundle\Entity\User
    registration:
        confirmation:
            enabled: true
        form:
            type: some_bundle_registration_type
    service:
        mailer: some_bundle.mailer

io_admin:
    admin_prefix: /admin
    user_class: SomeBundle\Entity\User
    admin_menu:
        #- { category: "Site Settings", path: "sitesettings", role: "ROLE_ADMIN" }